<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="1" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Test Suite" duration-ms="168739" started-at="2020-08-01T13:06:02 IST" finished-at="2020-08-01T13:08:51 IST">
    <groups>
    </groups>
    <test name="Application Test" duration-ms="168739" started-at="2020-08-01T13:06:02 IST" finished-at="2020-08-01T13:08:51 IST">
      <class name="com.PracticeTestClasses.TestClasses.LoginTests">
        <test-method status="PASS" signature="commonSetUp(java.lang.String)[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="commonSetUp" is-config="true" duration-ms="29721" started-at="2020-08-01T13:06:02 IST" finished-at="2020-08-01T13:06:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commonSetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="setUp" is-config="true" duration-ms="0" started-at="2020-08-01T13:06:32 IST" finished-at="2020-08-01T13:06:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="methodSetUp" is-config="true" duration-ms="78" started-at="2020-08-01T13:06:32 IST" finished-at="2020-08-01T13:06:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="FAIL" signature="testLogin()[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="testLogin" duration-ms="22505" started-at="2020-08-01T13:06:32 IST" finished-at="2020-08-01T13:06:54 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.PracticePageClasses.Pages.NavigationPage.verifyHeader(NavigationPage.java:55)
at com.PracticeTestClasses.TestClasses.LoginTests.testLogin(LoginTests.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="afterMethod" is-config="true" duration-ms="10107" started-at="2020-08-01T13:06:55 IST" finished-at="2020-08-01T13:07:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.PracticeTestClasses.TestClasses.LoginTests@550dbc7a]" name="tearDown" is-config="true" duration-ms="1015" started-at="2020-08-01T13:07:05 IST" finished-at="2020-08-01T13:07:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.PracticeTestClasses.TestClasses.LoginTests -->
      <class name="com.PracticeTestClasses.TestClasses.AllCoursesTest">
        <test-method status="PASS" signature="commonSetUp(java.lang.String)[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="commonSetUp" is-config="true" duration-ms="18081" started-at="2020-08-01T13:07:06 IST" finished-at="2020-08-01T13:07:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commonSetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="setUp" is-config="true" duration-ms="13208" started-at="2020-08-01T13:07:24 IST" finished-at="2020-08-01T13:07:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="filterByCategory()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="filterByCategory" duration-ms="58451" started-at="2020-08-01T13:07:37 IST" finished-at="2020-08-01T13:08:36 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.PracticePageClasses.Pages.CategoryFilterPage.findCoursesCount(CategoryFilterPage.java:41)
at com.PracticeTestClasses.TestClasses.AllCoursesTest.filterByCategory(AllCoursesTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- filterByCategory -->
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="methodSetUp" is-config="true" duration-ms="0" started-at="2020-08-01T13:07:37 IST" finished-at="2020-08-01T13:07:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="methodSetUp()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="methodSetUp" is-config="true" duration-ms="1" started-at="2020-08-01T13:08:36 IST" finished-at="2020-08-01T13:08:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="FAIL" signature="verifySearchCourse()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="verifySearchCourse" duration-ms="13077" started-at="2020-08-01T13:08:36 IST" finished-at="2020-08-01T13:08:49 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.PracticeTestClasses.TestClasses.AllCoursesTest.verifySearchCourse(AllCoursesTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearchCourse -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.PracticeTestClasses.TestClasses.AllCoursesTest@21282ed8]" name="tearDown" is-config="true" duration-ms="908" started-at="2020-08-01T13:08:50 IST" finished-at="2020-08-01T13:08:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.PracticeTestClasses.TestClasses.AllCoursesTest -->
    </test> <!-- Application Test -->
  </suite> <!-- Regression Test Suite -->
</testng-results>
